
version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=products_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db:/docker-entrypoint-initdb.d
      - ./docker/data:/var/lib/postgresql/data
